<?php
/**
  * Implementation of hook_menu().
  */
function jstree_menu() {
   $items['species_index'] = array(
      'title' => 'ดัชนีสิ่งมีชีวิต Species Index', 
      'description' => 'Jstree',
      'page callback' => 'jstree_render',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    //  'file' => 'siamensis_hooker_admin.inc',
      'file'=> 'jstree_render.inc',
   );
   $items['json'] = array(
      'title' => 'Json', 
      'description' => 'Jsone',
      'page callback' => 'json',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
      'file'=> 'jstree_render.inc',
   );
  $items['species_index/node/%node'] = array(
    'page callback' => 'jstree_node',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file'=> 'jstree_render.inc',
  );
  
  $items['admin/settings/jstree'] = array(
    'title' => 'Jstree settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jstree_admin_settings'),
    'access arguments' => array('administer nodes'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'jstree.admin.inc',
  );
 
   return $items;
}

/**
 * Implementation of hook_nodeapi.
 */
function jstree_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'insert') {
    // I'm not sure hook_nodeapi() run before / after rules?
    if ($node->status < 1 && !user_access('administer nodes')) { // Unpublish
      drupal_set_message(t('Your newly index has been saved, wait for administrator approve then index would be publish.'));
    }
  }
}

function jstree_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] === 'node-form' && !empty($form['nid']['#value'])) {
    // Find children nodes.
    if (isset($form['buttons']['delete']) && $form['#node']->book['has_children'] == 1) {
       unset($form['buttons']['delete']);
       drupal_set_message(t('Found children in this content, so content deletion has been disabled until all children are removed.'), 'warning');
    }
  }
}
