<?php
$map_year_list = array();
define('HELMET_LEVEL0_COLOR', '#D2D2D2');
define('HELMET_LEVEL1_COLOR', '#e30613');
define('HELMET_LEVEL2_COLOR', '#f39200');
define('HELMET_LEVEL3_COLOR', '#ffed00');
define('HELMET_LEVEL4_COLOR', '#3aaa35');
define('HELMET_LEVEL5_COLOR', '#3d6128');

/**
 * Implementation of hook_perm().
 */
function helmet_perm() {
  return array(
    'import helmet data',
  );
}

/**
 * Implementation of hook_menu().
 */
function helmet_menu() {

  $items['admin/settings/helmetimport'] = array(
    'title' => 'Helmet Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('helmet_provincial_import_form', 'all'),
    'access arguments' => array('import helmet data'),
    'file' => 'includes/helmet.provincial.inc',
  );


  $items['admin/settings/helmetimport/provincial'] = array(
    'title' => 'Helmet Provincial',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('helmet_provincial_import_form', 'provincial'),
    'access arguments' => array('import helmet data'),
    'file' => 'includes/helmet.provincial.inc',
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/settings/helmetimport/regional'] = array(
    'title' => 'Helmet Regional',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('helmet_provincial_import_form', 'regional'),
    'access arguments' => array('import helmet data'),
    'file' => 'includes/helmet.provincial.inc',
    'weight' => -1,
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/settings/helmetimport/all'] = array(
    'title' => 'Helmet All',
    'weight' => -2,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['statistic/helmet'] = array(
    'title' => 'อัตราการสวมหมวกนิรภัยของผู้ใช้รถจักรยานยนต์ในประเทศไทย',
    'page callback' => 'helmet_statistic_catagory_list',
    'access arguments' => array('access content'),
  );

  $items['statistic/helmet/provincial/%'] = array(
    'page callback' => 'helmet_statistic_map_view',
    'access arguments' => array('access content'),
  );

  $items['statistic/helmet/overview/%'] = array(
    'page callback' => 'helmet_statistic_chart_view',
    'access arguments' => array('access content'),
  );

  $items['helmet/mapdata'] = array(
    'page callback' => 'helmet_get_map_data',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['helmet/dashboard_data'] = array(
    'page callback' => 'helmet_get_dashboard_data',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['helmet/chartdata'] = array(
    'page callback' => 'helmet_get_chart_data',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['helmet/yearlist'] = array(
    'page callback' => 'helmet_get_year_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function helmet_statistic_chart_view() {

  $breadcrumb_title = 'อัตราการสวมหมวกนิรภัยในภาพรวม';
  // Todo remove hard code
  if (arg(3) == 294) {

    $code_detail = array(
      'รวมผู้ขับขี่และผู้โดยสาร' => 'C5_01-C2_01',
      'เฉพาะผู้ขับขี่' => 'C5_01-C2_02',
      'เฉพาะผู้โดยสาร' => 'C5_01-C2_03',
    );
    $breadcrumb_title .= 'ทั้งประเทศ';
    $chart_title = 'ในภาพรวม';
  }
  elseif (arg(3) == 295) {

    $filter_cat = array(
      'รวมผู้ขับขี่และผู้โดยสาร' => 'C5_02-C2_01',
      'เฉพาะผู้ขับขี่' => 'C5_02-C2_02',
      'เฉพาะผู้โดยสาร' => 'C5_02-C2_03',
    );
    $chart_type = 'column';
    $breadcrumb_title .= 'จำแนกตามภูมิภาค';
  }
  elseif (arg(3) == 296) {

    $code_detail = array(
      'ผู้ใหญ่' => 'C5_03-C3_01',
      'วัยรุ่น' => 'C5_03-C3_02',
      'เด็ก' => 'C5_03-C3_03',
    );
    $breadcrumb_title .= 'จำแนกตามกลุ่มผู้ใช้รถจักรยานยนต์';
    $chart_title = 'จำแนกตามกลุ่มผู้ใช้รถจักรยานยนต์';

  }
  elseif (arg(3) == 297) {

    $code_detail = array(
      'ชุมชนเมืองหลัก' => 'C5_04-C2_01-C4_01',
      'ชนบท' => 'C5_04-C2_01-C4_02',
      'ชุมชนเมืองรอง' => 'C5_04-C2_01-C4_03',
    );
    $breadcrumb_title .= 'จำแนกตามพื้นที่';
    $chart_title = 'จำแนกตามพื้นที่';
    $remark_text = '<div class="remark -helmet">
      <h3 class="title">หมายเหตุ</h3>
      <strong>ชุมชนเมืองหลัก</strong> หมายถึง เขตเทศบาลนครหรือเทศบาลเมืองที่เป็นศูนย์กลางกิจกรรมทางเศรษฐกิจของจังหวัด
      <br />
      <strong>ชุมชนเมืองรอง</strong> หมายถึง เขตเทศบาลเมืองในอําเภออื่นๆ หรือเทศบาลตําบลที่มีประชากรมากกว่า 20,000 คน
      <br />
      <strong>ชุมชนชนบท</strong> หมายถึง เทศบาลตําบลที่มีประชากรน้อยกว่า 20,000 คน
    </div>';

    $filter_cat = array(
      'รวมผู้ขับขี่และโดยสาร' => 'C5_04-C2_01-C4_01,C5_04-C2_01-C4_02',
      'เฉพาะผู้ขับขี่' => 'C5_04-C2_02-C4_01,C5_04-C2_02-C4_02',
      'เฉพาะผู้โดยสาร' => 'C5_04-C2_03-C4_01,C5_04-C2_03-C4_02',
    );

  }

  $output .= '<div id="filter-year" class="form-group -helmet">
          <label>ข้อมูลสถิติในช่วงปี. พ.ศ. </label>
          <select id="start_year" class="form-control"></select>
          <label class="to_year">ถึง ปี พ.ศ. </label>
          <select id="end_year" class="form-control"></select>
  ';
  $output .= '<input id="filter_btn" type="button" class="btn btn-primary" value="เลือก">';
  $output .= '</div>';

  if (isset($filter_cat)) {
    $output .= '<div id="filter-cate" class="form-group -helmet">
                <label>ตำแหน่งที่นั่ง</label>
                <select id="position_filter" class="form-control">
                ';
    foreach ($filter_cat as $key => $value) {
      $output .= '<option value='.$value.'>'.$key.'</option>';
    }
    $output .= '</select>';
    $output .= '<input id="position_filter_btn" type="button" class="btn btn-primary" value="เลือก">';
    $output .= '</div>';
  }

  if (isset($chart_type)) {
    $output .= '<input type="hidden" value="'.$chart_type.'" id="chart_type">';
  }
  if (isset($chart_title)) {

      $output .= '<input class="chart-title-hidden" type="hidden" value="'.$chart_title.'">';
  }
  if (isset($code_detail)) {
    $runNum = 0;
    foreach ($code_detail as $key => $value) {
      $output .= '<input class="code-value-filter-hidden" type="hidden" value="'.$value.'" name="code_value['.$runNum.']">';
      $output .= '<input class="code-name-filter-hidden" type="hidden" value="'.$key.'" name="code_name['.$runNum.']">';
      $runNum++;
    }

  }
  drupal_set_title('อัตราการสวมหมวกนิรภัยของผู้ใช้รถจักรยานยนต์ในประเทศ');
  // Build Breadcrumbs
  $breadcrumb = array();
  $breadcrumb[] = l(t('Home'), '<front>');
  $breadcrumb[] = l('สถิติและข้อมูล', 'statistic');
  $breadcrumb[] = l('อัตราการสวมหมวกนิรภัย', 'statistic/helmet');
  $breadcrumb[] = $breadcrumb_title; // Link to current URL
  // Set Breadcrumbs

  drupal_set_breadcrumb($breadcrumb);

  drupal_add_js(drupal_get_path('module', 'helmet').'/js/highcharts.src.js');
  drupal_add_js(drupal_get_path('module', 'helmet').'/js/renderchart.js');
  $output .= '<div id="container" style="min-width: 310px; min-height: 400px; margin: 0 auto"></div>';

  if (isset($remark_text)) {
    $output .= $remark_text;
  }

  $output .= '<div class="print-wrapper"><input type="button" value="'.t('print').'" onclick="window.print();" class="print-btn -helmet"></div>';
  return $output;
}
$map_year_list;
function helmet_get_value_from_code($code, $year_start, $year_end, &$map_year_list) {

  $sql = "SELECT nid FROM node WHERE title = '%s' AND type = 'helmet_statistic' ORDER BY changed";
  $q   = db_query($sql, $code);
  $result = array();
  while ($row = db_fetch_array($q)) {

    $node = node_load($row['nid']);
    $map_year_list = array();
    foreach ($node->field_year_value as $kn => $item) {
        $map_year_list[] = $item['key'];
        if ($item['key'] >= $year_start && $item['key'] <= $year_end) {
          $result[$item['key']] = intval($item['value']);
        }
    }

  }
  return $result;

}

function helmet_get_year_list() {

  $code = $_POST['code'];

  $sql = "SELECT nid FROM node WHERE title = '%s' AND type = 'helmet_statistic' ORDER BY changed";
  $q   = db_query($sql, $code);
  while ($row = db_fetch_array($q)) {

    $node = node_load($row['nid']);
    $map_year_list = array();
    foreach ($node->field_year_value as $kn => $item) {
        $map_year_list[] = $item['key'];
    }

  }

  drupal_json($map_year_list);
  exit();


}

function helmet_get_value_from_code_with_area($code, $year_start, $year_end) {

  $sql = "SELECT nid FROM node WHERE title = '%s' AND type = 'helmet_statistic'";
  $q   = db_query($sql, $code);
  $data = array();
  while ($row = db_fetch_array($q)) {
    $node = node_load($row['nid']);

    // Get area of node
    foreach ($node->taxonomy as $key => $value) {

      if ($value->vid == 2 && $value->tid != 42) {

        $result = array();
        foreach ($node->field_year_value as $kn => $item) {
            if ($item['key'] >= $year_start && $item['key'] <= $year_end) {
              $result[$item['key']] = intval($item['value']);
            }
            $data[$value->name] = $result;
        }



      }
    }

  }
  return $data;
}

function helmet_get_chart_data() {
  //if (empty($_POST["year"])){ die(); }

  $code_name_list = $_POST["code_name"];
  $code_value_list = $_POST["code_value"];
  $year_start = $_POST["yearStart"];
  $year_end = $_POST["yearEnd"];
  $with_area = $_POST['withArea'];

  if ($with_area) {
    $code = $_POST['code'];
    $result_json = helmet_get_value_from_code_with_area($code, $year_start, $year_end);
    return drupal_json($result_json);
  }
  else {

    $result_json_main = array();
    $result_json = array();
    foreach ($code_value_list as $key => $value) {
      $result_json[$code_name_list[$key]] =  helmet_get_value_from_code($value, $year_start, $year_end ,$map_year_list);
    }

  }
  $result_json_main['data'] = $result_json;
  $result_json_main['year_list'] = $map_year_list;

  drupal_json($result_json_main);
  exit();


}

function helmet_statistic_catagory_list() {

  drupal_add_js(drupal_get_path('module', 'helmet').'/js/dashboard_data.js');
  drupal_add_js(drupal_get_path('module', 'helmet').'/js/progress-circle.js');
  drupal_add_css(drupal_get_path('module', 'helmet').'/css/circle.css');
  drupal_add_css(drupal_get_path('module', 'helmet').'/css/helmet.css');

  $category_list = taxonomy_get_tree(10);
  $category_list2 = taxonomy_get_tree(6);
  $output = '<div class="description -helmet">ข้อมูลผลการสํารวจอัตราการสวมหมวกนิรภัยของผู้ใช้รถจักรยานยนต์ในประเทศไทย ตั้งแต่ปี พ.ศ. 2553 จนถึงปัจจุบัน โดยมูลนิธิไทยโรดส์ และสถาบันการศึกษาท่ัวประเทศของเครือข่ายเฝ้าระวังสถานการณ์ความปลอดภัยทางถนน (Road Safety Watch) ภายใต้การสนับสนุนของ สํานักงานกองทุนสนับสนุนการสร้างเสริมสุขภาพ (สสส.)</div>';
  $output .= '<div class="helmet-dashboard"><p class="loading">';
  $province_list = taxonomy_get_tree(2, 48);
  // Todo remove dummy code;
  $year_list = array(1, 2, 3);
  $init_data = array(
    'position' => array(42, 51 ,19),
    'age' => array(47, 7 ,22),
    'area' => array(
      'all' => array(70, 45 ,31, 43),
      'driver' => array(81, 54, 37, 51),
      'passenger' => array(35, 19, 15, 20),
    ),
  );
//helmet_get_dashboard_data();
  $output .= '</p>';
  $output .= theme('helmet_dashboard', $province_list, $year_list, $init_data);
  $output .= '</div>';

  $output .= '<div class="descriptionTitle -helmet"><h3>
            แนวโน้มอัตราการสวมหมวกนิรภัยจากอดีตถึงปัจจุบัน</h3></div><ul class="helmet-list">';

  foreach ($category_list as $value) {
    $output .= '<li>'.l($value->name, 'statistic/helmet/overview/'.$value->tid).'</li>';
  }
  $output .= '</ul>';
  $output .= '<div class="descriptionTitle -helmet"><h3>
            แผนที่สารสนเทศภูมิศาสตร์ (GIS) อัตราการสวมหมวกนิรภัยรายจังหวัด
            </h3></div><ul class="helmet-list">';

  foreach ($category_list2 as $value) {
    $output .= '<li>'.l($value->name, 'statistic/helmet/provincial/'.$value->tid).'</li>';
  }
  $output .= '</ul>';

  $breadcrumb = array();
  $breadcrumb[] = l(t('Home'), '<front>');
  $breadcrumb[] = l('สถิติและข้อมูล', 'statistic');
  $breadcrumb[] = 'อัตราการสวมหมวกนิรภัย';
  // Set Breadcrumbs

  drupal_set_breadcrumb($breadcrumb);
  drupal_add_js("
    $(document).ready(function () {
      $('.page-title').addClass('page-helmet');
    });
    "
    , 'inline');

  return $output;
}

function helmet_statistic_map_view() {

  // Todo remove hardcode
  $filter_cat = NULL;
  if (arg(3) == 281) {
    $code_detail = array(
      'id' => array(
        'C1_01-C2_01',
        'C1_01-C2_02',
        'C1_01-C2_03'
      ),
      'name' => array(
        'รวมผู้ขับขี่และโดยสาร',
        'เฉพาะผู้ขับขี่',
        'เฉพาะผู้โดยสาร'
      ),
    );
    $map_heading_type = '';
    $map_name = 'map-all';
  }
  elseif (arg(3) == 282) {

    $code_detail = array(
      'id' => array(
        'C1_02-C2_01-C3_01',
        'C1_02-C2_01-C3_02',
        'C1_02-C2_03-C3_03'
      ),
      'name' => array(
        'ผู้ใหญ่',
        'วัยรุ่น',
        'เด็ก'
      ),
    );
    $map_heading_type = 'จำแนกตามกลุ่มผู้ใช้รถจักรยานยนต์';
    $map_name = 'map-age';

  }
  elseif (arg(3) == 283) {
    $code_detail = array(
      'id' => array(
        'C1_03-C2_01-C4_01',
        'C1_03-C2_01-C4_02',
        'C1_03-C2_01-C4_03',
      ),
      'name' => array(
        'เขตชุมชนเมืองหลัก',
        'เขตชุมชนชนบท',
        'เขตชุมชนเมืองรอง',
      ),
    );
    $map_heading_type = 'จำแนกตามพื้นที่';
    $map_name = 'map-area';

    $filter_cat = array(
      'รวมผู้ขับขี่และโดยสาร' => 'C1_03-C2_01-C4_01,C1_03-C2_01-C4_02',
      'เฉพาะผู้ขับขี่' => 'C1_03-C2_02-C4_01,C1_03-C2_02-C4_02',
      'เฉพาะผู้โดยสาร' => 'C1_03-C2_03-C4_01,C1_03-C2_03-C4_02',
    );

  }


  drupal_add_js(drupal_get_path('module', 'helmet').'/js/jquery.svg.package/jquery.svg.js');
  drupal_add_js(drupal_get_path('module', 'helmet').'/js/load_csv.js');
  drupal_add_js(drupal_get_path('module', 'helmet').'/js/print_toggle.js');
  $term = taxonomy_get_term(arg(3));
  $term_field = term_fields_get_fields($term);

  // $term_list[HELMET_LEVEL0_COLOR] = array('start' => $term_field['helmet_level0'], 'end' => $term_field['helmet_level0'], 'img' => 'level-0.png');
  $term_list[HELMET_LEVEL1_COLOR] = array('start' => $term_field['helmet_level1_start'], 'end' => $term_field['helmet_level1_end'], 'img' => 'level-1.png');
  $term_list[HELMET_LEVEL2_COLOR] = array('start' => $term_field['helmet_level2_start'], 'end' => $term_field['helmet_level2_end'], 'img' => 'level-2.png');
  $term_list[HELMET_LEVEL3_COLOR] = array('start' => $term_field['helmet_level3_start'], 'end' => $term_field['helmet_level3_end'], 'img' => 'level-3.png');
  $term_list[HELMET_LEVEL4_COLOR] = array('start' => $term_field['helmet_level4_start'], 'end' => $term_field['helmet_level4_end'], 'img' => 'level-4.png');
  $term_list[HELMET_LEVEL5_COLOR] = array('start' => $term_field['helmet_level5_start'], 'end' => $term_field['helmet_level5_end'], 'img' => 'level-5.png');
  //drupal_set_title($term->name);
  drupal_set_title('อัตราการสวมหมวกนิรภัยของผู้ใช้รถจักรยานยนต์ในประเทศ');
  $province_list = taxonomy_get_tree(2, 48);
  $map_description = $term->description;

  // Build Breadcrumbs
  $breadcrumb = array();
  $breadcrumb[] = l(t('Home'), '<front>');
  $breadcrumb[] = l('สถิติและข้อมูล', 'statistic');
  $breadcrumb[] = l('อัตราการสวมหมวกนิรภัย', 'statistic/helmet');
  $breadcrumb[] = $term->name; // Link to current URL
  // Set Breadcrumbs

  drupal_set_breadcrumb($breadcrumb);
  return theme('helmet_map', $term_list, $province_list, arg(3), $code_detail, $term->name, $filter_cat, $map_heading_type, $map_name);

}

function helmet_get_dashboard_data() {

  if (empty($_POST["year"])){ die(); }

  $codes = array(
    'C1_01-C2_01',
    'C1_01-C2_02',
    'C1_01-C2_03',

    'C1_02-C2_01-C3_01',
    'C1_02-C2_03-C3_03',
    'C1_02-C2_01-C3_02',

    'C1_03-C2_01-C4_01',
    'C1_03-C2_01-C4_03',
    'C1_03-C2_01-C4_02',
    'C1_03-C2_01-C4_04',

    'C1_03-C2_02-C4_01',
    'C1_03-C2_02-C4_03',
    'C1_03-C2_02-C4_02',
    'C1_03-C2_02-C4_04',

    'C1_03-C2_03-C4_01',
    'C1_03-C2_03-C4_03',
    'C1_03-C2_03-C4_02',
    'C1_03-C2_03-C4_04',

  );
  $year = $_POST['year'];
  $province_id = $_POST['provinceId'];
  $result_json = array();
  $year_list = array();
  $data = array();
  foreach($codes as $code) {
    $sql = "SELECT n.nid FROM node n INNER JOIN term_node tn ON n.nid = tn.nid WHERE n.title = '%s' AND tn.tid = %d";
    $q   = db_query($sql, $code, $province_id);
    while ($row = db_fetch_array($q)) {
      $node = node_load($row['nid']);
      foreach ($node->field_year_value as $kn => $item) {
        if ($item['key'] == $year) {
          $data[] = $item['value'];
        }
      }
    }

  }


  $result_json = array(
    'position' => array($data[0], $data[1], $data[2]),
    'age' => array($data[3], $data[4], $data[5]),
    'area' => array(
      'all' => array($data[6], $data[7], $data[8], $data[9]),
      'driver' => array($data[10], $data[11], $data[12], $data[13]),
      'passenger' => array($data[14], $data[15], $data[16], $data[17]),
    ),
  );
  drupal_json($result_json);
  exit();
}

$co = '#000';
function helmet_get_map_data() {
  if (empty($_POST["year"])){ die(); }
  // dummy range color

  $code = $_POST['code'];
  $year = $_POST['year'];
  $cat_id = $_POST['catId'];

  $level0_color = HELMET_LEVEL0_COLOR;
  $level1_color = HELMET_LEVEL1_COLOR;
  $level2_color = HELMET_LEVEL2_COLOR;
  $level3_color = HELMET_LEVEL3_COLOR;
  $level4_color = HELMET_LEVEL4_COLOR;
  $level5_color = HELMET_LEVEL5_COLOR;

  $term = taxonomy_get_term($cat_id);
  $term = term_fields_get_fields($term);
  $check_term = helmet_map_check_color_field($term);
  if ($check_term) {
    $level1_end = $term['helmet_level1_end'];
    $level2_end = $term['helmet_level2_end'];
    $level3_end = $term['helmet_level3_end'];
    $level4_end = $term['helmet_level4_end'];
    $sub_cate_term = true;

  }
  else {
    $level1_end = 999999999999999;
    $level1_color = '#ddd';
    $sub_cate_term = false;
  }

  $province_list = taxonomy_get_tree(2, 48);
  // Load data each province
  $result_json = array();
  $result_json['subCateTerm'] = $sub_cate_term;

  foreach($province_list as $k => $province) {
    $sql = "SELECT n.nid FROM node n INNER JOIN term_node tn ON n.nid = tn.nid WHERE n.title = '%s' AND tn.tid = %d";
    $q   = db_query($sql, $code, $province->tid);
    // Default color
    $result_json[$province->tid] = array('name' => $province->name, 'value' => 'ไม่มีข้อมูล', 'color' => '#ddd');
    while ($row = db_fetch_array($q)) {
      $node = node_load($row['nid']);
      $total_value = 0;
      $run_id = 0;
      foreach ($node->field_year_value as $kn => $item) {
        $map_year_list[] = $item['key'];
        if ($item['key'] == $year) {
          $run_id++;
          $total_value = $item['value'];
          if ($item['value'] != 'N/A') {
            $value = $total_value;
            if ($value == '-') {
              $color = $level0_color;
            }
            elseif ($value <= $level1_end) {
              $color = $level1_color;
            }
            // if ($value <= $level1_end) {
            //   $color = $level1_color;
            // }
            elseif ($value <= $level2_end) {
              $color = $level2_color;
            }
            elseif ($value <= $level3_end) {
              $color = $level3_color;
            }
            elseif ($value <= $level4_end) {
              $color = $level4_color;
            }
            else {
              $color = $level5_color;
            }
            //$value = number_format($value, 3);
            if ($value == '-') {
              $value = 'ไม่มีข้อมูลชุมชนเมืองรอง';
              $result_json[$province->tid] = array('name' => $province->name, 'value' => $value, 'color' => $color);
            }
            else {
              $value = thairoads_num_format($value);
              $result_json[$province->tid] = array('name' => $province->name, 'value' => $value.'%', 'color' => $color);
            }
          }
        }
      }

    }
  }
  $map_year_list = array_unique($map_year_list);
  rsort($map_year_list);
  $result_json['map_year_list'] = $map_year_list;
  drupal_json($result_json);
  exit();

}

function helmet_map_check_color_field($term_field_data) {
  $fields = array('helmet_level1_start', 'helmet_level1_end', 'helmet_level2_start', 'helmet_level2_end', 'helmet_level3_start', 'helmet_level3_end', 'helmet_level4_start', 'helmet_level4_end', 'helmet_level5_start');
  foreach($fields as $field) {
    if (is_null($term_field_data[$field]) || $term_field_data[$field] == '') {
      return false;
    }
  }
  return true;
}

/**
 * Implementation of hook_theme().
 */
function helmet_theme() {
  return array(
    'helmet_provincial_import_form' => array(
      'arguments' => array('element' => NULL),
    ),
    'helmet_map' => array(
      'arguments' => array(
        'term_list' => NULL,
        'province_list' => NULL,
        'cate_id' => NULL,
        'code_detail' => NULL,
        'term_name' => NULL,
        'filter_cat' => NULL,
        'map_heading_type' => NULL,
        'map_name' => NULL,
       ),
      'template' => 'helmet-map',
    ),
    'helmet_dashboard' => array(
      'arguments' => array(
        'province_list' => NULL,
        'year_list' => NULL,
        'init_data' => NULL,
       ),
      'template' => 'helmet-dashboard',
    ),
  );
}

/**
 *
 */
function theme_helmet_provincial_import_form($element) {
  $rows = array();
  $form_type = $element['form_type']['#value'];
  foreach (element_children($element) as $key) {
    if ($element[$key]['#type'] == 'file') {
      $code = $element[$key]['#title'];
      $submit = array(
        '#type' => 'submit',
        '#value' => t('Import'),
      );
      unset($element[$key]['#title']);

      // Code sescription for provincial form
      if ($form_type == 'provincial') {
        $terms = helmet_get_tree_by_code($code);
        $term_text = '';
        foreach ($terms as $key_term => $value_term) {
          $term_text .= $value_term->name.' ';
        }

      }
      $rows[] = array(
        $code .' '.$term_text,
        drupal_render($element[$key]),
        drupal_render($submit),
      );
    }
  }

  $header = array(
    t('Code'),
    t('Upload'),
    t('Import'),
  );
  $output = '';

  if ($form_type == 'all') {
    $output .= 'อัตราการสวมหมวกนิรภัยในภาพรวมทั้งประเทศ';
  }
  elseif ($form_type == 'regional') {
    $output .= 'อัตราการสวมหมวกนิรภัยในภาพรวมทั้งประเทศ จำแนกตามภาค';
  }
  elseif ($form_type == 'provincial') {
    $output .= 'อัตราการสวมหมวกนิรภัยรายจังหวัด';
  }
  $output .= drupal_render($element['table']);
  $output .= '<h3>'. t('Import file') .'</h3>';
  $output .= theme('table', $header, $rows);
  $output .= drupal_render($element);
  return $output;
}

function _helmet_get_provincial_code($type='provincial') {

  if ($type == 'provincial') {

    $code = array(
      'C1_01-C2_01',
      'C1_01-C2_02',
      'C1_01-C2_03',

      'C1_02-C2_01-C3_01',
      'C1_02-C2_01-C3_02',
      'C1_02-C2_03-C3_03',

      'C1_03-C2_01-C4_01',
      'C1_03-C2_01-C4_02',
      'C1_03-C2_01-C4_03',
      'C1_03-C2_01-C4_04',
      'C1_03-C2_02-C4_01',
      'C1_03-C2_02-C4_02',
      'C1_03-C2_02-C4_03',
      'C1_03-C2_02-C4_04',
      'C1_03-C2_03-C4_01',
      'C1_03-C2_03-C4_02',
      'C1_03-C2_03-C4_03',
      'C1_03-C2_03-C4_04',
    );
  }
  elseif ($type == 'regional') {
    $code = array(
      'C5_02_ALL',
    );
  }
  elseif ($type == 'all') {
    $code = array(
      'C5_ALL',
    );
  }

  return $code;
}

function helmet_get_tree_by_code($code) {
  $tree = array();
  $term_array = explode('-', $code);
  foreach ($term_array as $value) {
    $term_value = explode('_', $value);
    $vid = db_result(db_query("SELECT vid FROM `vocabulary` WHERE name LIKE('%[%s]')", $term_value[0]));
    $tid = db_result(db_query("SELECT td.tid FROM term_data td LEFT JOIN term_synonym ts ON td.tid = ts.tid WHERE vid = %d AND ts.name = %s", $vid,$term_value[1]));
    $tree[] = taxonomy_get_term($tid);
  }
  return $tree;
}

function helmet_get_node_by_code_area($code, $area, $type = 'nid') {
  if (!is_null($area)) {
    $sql = "SELECT n.nid
          FROM node n
          INNER JOIN term_node tn
          ON n.nid = tn.nid
          INNER JOIN term_fields_term tf
          ON tn.tid = tf.tid
          WHERE n.title = '%s' AND tf.field_area_id = '%s'
          ";
    $nid = db_result(db_query($sql, $code, $area));

  }
  else {
    $sql = "SELECT n.nid
          FROM node n
          WHERE n.title = '%s' ORDER BY n.changed DESC
          ";
    $nid = db_result(db_query($sql, $code));

  }
  if ($nid) {
    $node = node_load($nid);
    switch ($type) {
      case 'nid': return $nid;
      case 'node': return $node;
      default: return $node->{$type};
    }
  }
  return NULL;
}
