<?php

/**
 * Implementation of hook_perm().
 */
function helmet_perm() {
  return array(
    'import helmet data',
  );
}

/**
 * Implementation of hook_menu().
 */
function helmet_menu() {
  $items['admin/settings/helmetimport/provincial'] = array(
    'title' => 'Provincial',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('helmet_provincial_import_form', 'provincial'),
    'access arguments' => array('import helmet data'),
    'file' => 'includes/helmet.provincial.inc',
    'weight' => 0,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function helmet_theme() {
  return array(
    'helmet_provincial_import_form' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

/**
 * 
 */
function theme_helmet_provincial_import_form($element) {
  $rows = array();
  foreach (element_children($element) as $key) {
    if ($element[$key]['#type'] == 'file') {
      $code = $element[$key]['#title'];
      $submit = array(
        '#type' => 'submit',
        '#value' => t('Import'),
      );
      unset($element[$key]['#title']);
      $rows[] = array(
        $code,
        drupal_render($element[$key]),
        drupal_render($submit),
      );
    }
  }

  $header = array(
    t('Code'),
    t('Upload'),
    t('Import'),
  );

  $output = drupal_render($element['table']);
  $output .= '<h3>'. t('Import file') .'</h3>';
  $output .= theme('table', $header, $rows);
  $output .= drupal_render($element);

  return $output;
}

function _helmet_get_provincial_code() {
  $code = array(
    'C1-01-C2-01',
    'C1-01-C2-02',
    'C1-01-C2-03',

    'C1-02-C2-01-C3-01',
    'C1-02-C2-01-C3-02',
    'C1-02-C2-01-C3-03',
    'C1-02-C2-02-C3-01',
    'C1-02-C2-02-C3-02',
    'C1-02-C2-02-C3-03',
    'C1-02-C2-03-C3-01',
    'C1-02-C2-03-C3-02',
    'C1-02-C2-03-C3-03',

    'C1-03-C2-01-C4-01',
    'C1-03-C2-01-C4-02',
    'C1-03-C2-02-C4-01',
    'C1-03-C2-02-C4-02',
    'C1-03-C2-03-C4-01',
    'C1-03-C2-03-C4-02',

  );
  return $code;
}
