<?php

/**
 * Implementation of hook_menu().
 */
function gvapi_menu() {
  $items['admin/settings/gvapi'] = array(
    'title' => t('Google Visualization API'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gvapi_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'gvapi.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_init().
 */
function gvapi_init() {
}

/**
 * Render visualization.
 */
function gvapi_render($data) {
  drupal_set_html_head('<script type="text/javascript" src="http://www.google.com/jsapi"></script>');
  drupal_add_js(array('gvapi' => $data), 'setting');
  drupal_add_js(drupal_get_path('module', 'gvapi') .'/gvapi.js');
}
